name: CTC
version: '${project.version}'
main: org.macl.ctc.Main
api-version: '1.20'
softdepend:
  - DecentHolograms
commands:
  ctc:
    description: CTC Commands
    usage: /<command>
  stats:
    description: Show your CTC stats
    usage: /stats
